import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const titleFont = localFont({
  src: '../public/fonts/AtAero-Regular.otf',
  variable: '--font-title',
});

const bodyFont = localFont({
  src: '../public/fonts/Elianto-Regular.otf',
  variable: '--font-body',
});
const thirdFont = localFont({
  src: '../public/fonts/kanopibrazil-regular.otf',
  variable: '--font-third',
});

const race_font = localFont({
  src: '../public/fonts/race_sport.otf',
  variable: '--font-race',
});

const Angelos = localFont({
  src: '../public/fonts/Angelos.ttf',
  variable: '--font-angelos',
});

const Flagfies = localFont({
  src: '../public/fonts/Flagfies.ttf',
  variable: '--font-flagfies',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${titleFont.variable} ${Flagfies.variable} ${Angelos.variable} ${bodyFont.variable} ${thirdFont.variable} ${race_font.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
